"""first migrate

Revision ID: e4ff98ee59a0
Revises: 
Create Date: 2021-11-07 17:03:55.695150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ff98ee59a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_data_comment'), 'comment_data', ['comment'], unique=False)
    op.create_index(op.f('ix_comment_data_plan_id'), 'comment_data', ['plan_id'], unique=False)
    op.create_index(op.f('ix_comment_data_user_id'), 'comment_data', ['user_id'], unique=False)
    op.create_table('message_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('recipient_name_id', sa.String(length=64), nullable=True),
    sa.Column('sender_name_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_data_message'), 'message_data', ['message'], unique=False)
    op.create_index(op.f('ix_message_data_plan_id'), 'message_data', ['plan_id'], unique=False)
    op.create_index(op.f('ix_message_data_recipient_name_id'), 'message_data', ['recipient_name_id'], unique=False)
    op.create_index(op.f('ix_message_data_sender_name_id'), 'message_data', ['sender_name_id'], unique=False)
    op.create_table('plan_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('evaluation', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_evaluation_comment'), 'plan_evaluation', ['comment'], unique=False)
    op.create_index(op.f('ix_plan_evaluation_evaluation'), 'plan_evaluation', ['evaluation'], unique=False)
    op.create_index(op.f('ix_plan_evaluation_plan_id'), 'plan_evaluation', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_evaluation_user_id'), 'plan_evaluation', ['user_id'], unique=False)
    op.create_table('planning_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('member_id', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('flag', sa.String(length=1), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_chat_comment'), 'planning_chat', ['comment'], unique=False)
    op.create_index(op.f('ix_planning_chat_flag'), 'planning_chat', ['flag'], unique=False)
    op.create_index(op.f('ix_planning_chat_member_id'), 'planning_chat', ['member_id'], unique=False)
    op.create_index(op.f('ix_planning_chat_plan_id'), 'planning_chat', ['plan_id'], unique=False)
    op.create_table('planning_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('planner', sa.String(length=64), nullable=True),
    sa.Column('contents', sa.String(length=64), nullable=True),
    sa.Column('application', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.Column('taglist', sa.String(length=64), nullable=True),
    sa.Column('flag', sa.String(length=1), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_data_application'), 'planning_data', ['application'], unique=False)
    op.create_index(op.f('ix_planning_data_contents'), 'planning_data', ['contents'], unique=False)
    op.create_index(op.f('ix_planning_data_flag'), 'planning_data', ['flag'], unique=False)
    op.create_index(op.f('ix_planning_data_image'), 'planning_data', ['image'], unique=False)
    op.create_index(op.f('ix_planning_data_planner'), 'planning_data', ['planner'], unique=False)
    op.create_index(op.f('ix_planning_data_taglist'), 'planning_data', ['taglist'], unique=False)
    op.create_index(op.f('ix_planning_data_title'), 'planning_data', ['title'], unique=False)
    op.create_table('planning_menber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('member_id', sa.String(length=64), nullable=True),
    sa.Column('flag', sa.String(length=1), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_menber_flag'), 'planning_menber', ['flag'], unique=False)
    op.create_index(op.f('ix_planning_menber_member_id'), 'planning_menber', ['member_id'], unique=False)
    op.create_index(op.f('ix_planning_menber_plan_id'), 'planning_menber', ['plan_id'], unique=False)
    op.create_table('user_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('receiver', sa.String(length=64), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('evaluation', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_evaluation_comment'), 'user_evaluation', ['comment'], unique=False)
    op.create_index(op.f('ix_user_evaluation_evaluation'), 'user_evaluation', ['evaluation'], unique=False)
    op.create_index(op.f('ix_user_evaluation_plan_id'), 'user_evaluation', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_evaluation_receiver'), 'user_evaluation', ['receiver'], unique=False)
    op.create_index(op.f('ix_user_evaluation_sender'), 'user_evaluation', ['sender'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('picture_path', sa.Text(), nullable=True),
    sa.Column('taglist', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_taglist'), 'users', ['taglist'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), server_default='<function uuid4 at 0x000001C129EE98B0>', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_taglist'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_evaluation_sender'), table_name='user_evaluation')
    op.drop_index(op.f('ix_user_evaluation_receiver'), table_name='user_evaluation')
    op.drop_index(op.f('ix_user_evaluation_plan_id'), table_name='user_evaluation')
    op.drop_index(op.f('ix_user_evaluation_evaluation'), table_name='user_evaluation')
    op.drop_index(op.f('ix_user_evaluation_comment'), table_name='user_evaluation')
    op.drop_table('user_evaluation')
    op.drop_index(op.f('ix_planning_menber_plan_id'), table_name='planning_menber')
    op.drop_index(op.f('ix_planning_menber_member_id'), table_name='planning_menber')
    op.drop_index(op.f('ix_planning_menber_flag'), table_name='planning_menber')
    op.drop_table('planning_menber')
    op.drop_index(op.f('ix_planning_data_title'), table_name='planning_data')
    op.drop_index(op.f('ix_planning_data_taglist'), table_name='planning_data')
    op.drop_index(op.f('ix_planning_data_planner'), table_name='planning_data')
    op.drop_index(op.f('ix_planning_data_image'), table_name='planning_data')
    op.drop_index(op.f('ix_planning_data_flag'), table_name='planning_data')
    op.drop_index(op.f('ix_planning_data_contents'), table_name='planning_data')
    op.drop_index(op.f('ix_planning_data_application'), table_name='planning_data')
    op.drop_table('planning_data')
    op.drop_index(op.f('ix_planning_chat_plan_id'), table_name='planning_chat')
    op.drop_index(op.f('ix_planning_chat_member_id'), table_name='planning_chat')
    op.drop_index(op.f('ix_planning_chat_flag'), table_name='planning_chat')
    op.drop_index(op.f('ix_planning_chat_comment'), table_name='planning_chat')
    op.drop_table('planning_chat')
    op.drop_index(op.f('ix_plan_evaluation_user_id'), table_name='plan_evaluation')
    op.drop_index(op.f('ix_plan_evaluation_plan_id'), table_name='plan_evaluation')
    op.drop_index(op.f('ix_plan_evaluation_evaluation'), table_name='plan_evaluation')
    op.drop_index(op.f('ix_plan_evaluation_comment'), table_name='plan_evaluation')
    op.drop_table('plan_evaluation')
    op.drop_index(op.f('ix_message_data_sender_name_id'), table_name='message_data')
    op.drop_index(op.f('ix_message_data_recipient_name_id'), table_name='message_data')
    op.drop_index(op.f('ix_message_data_plan_id'), table_name='message_data')
    op.drop_index(op.f('ix_message_data_message'), table_name='message_data')
    op.drop_table('message_data')
    op.drop_index(op.f('ix_comment_data_user_id'), table_name='comment_data')
    op.drop_index(op.f('ix_comment_data_plan_id'), table_name='comment_data')
    op.drop_index(op.f('ix_comment_data_comment'), table_name='comment_data')
    op.drop_table('comment_data')
    # ### end Alembic commands ###
